export enum NOTIFICATION_PATTERN {
  NOTIFY = 'notify',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  SYSTEM_NOTIFICATION_SENT = 'SYSTEM_NOTIFICATION_SENT',
  LOGIN = 'login',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  RESEND = 'RESEND',
  HEALTHY_CHECK = 'HEALTHY_CHECK',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  USER_OFFLINE = 'USER_OFFLINE',
}

export enum UPLOADER_PATTERN {
  UPLOAD = 'UPLOAD',
}
